/**
 * Warning severity levels — warnings only; never hard-reject.
 */
export const WarningSeverity = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
} as const;

export type WarningSeverityValue = (typeof WarningSeverity)[keyof typeof WarningSeverity];

/**
 * Deterministic validation warning codes.
 */
export const ValidationWarningCode = {
  MISSING_BILL_DATE: 'MISSING_BILL_DATE',
  MISSING_DUE_DATE: 'MISSING_DUE_DATE',
  MISSING_INVOICE_DATE: 'MISSING_INVOICE_DATE',
  MISSING_INVOICE_NUMBER: 'MISSING_INVOICE_NUMBER',
  MISSING_SUPPLIER_NAME: 'MISSING_SUPPLIER_NAME',
  MISSING_UTILITY_PROVIDER: 'MISSING_UTILITY_PROVIDER',
  MISSING_CONSUMER_NUMBER: 'MISSING_CONSUMER_NUMBER',
  MISSING_ACCOUNT_NUMBER: 'MISSING_ACCOUNT_NUMBER',
  MISSING_QUANTITY: 'MISSING_QUANTITY',
  MISSING_RATE_PER_LITRE: 'MISSING_RATE_PER_LITRE',
  MISSING_BILLING_PERIOD: 'MISSING_BILLING_PERIOD',
  MISSING_TOTAL_AMOUNT: 'MISSING_TOTAL_AMOUNT',
  MISSING_UNITS_CONSUMED: 'MISSING_UNITS_CONSUMED',
  MISSING_CONTRACT_DEMAND: 'MISSING_CONTRACT_DEMAND',
  MISSING_MAXIMUM_DEMAND: 'MISSING_MAXIMUM_DEMAND',
  MISSING_CONSUMPTION_VOLUME: 'MISSING_CONSUMPTION_VOLUME',
  MISSING_UNIT: 'MISSING_UNIT',
  MISSING_GST_AMOUNT: 'MISSING_GST_AMOUNT',
  MISSING_COAL_GRADE: 'MISSING_COAL_GRADE',
  MISSING_GCV: 'MISSING_GCV',
  MISSING_MOISTURE: 'MISSING_MOISTURE',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',

  NEGATIVE_QUANTITY: 'NEGATIVE_QUANTITY',
  NEGATIVE_CONSUMPTION: 'NEGATIVE_CONSUMPTION',
  NEGATIVE_AMOUNT: 'NEGATIVE_AMOUNT',
  NEGATIVE_GST: 'NEGATIVE_GST',
  NEGATIVE_RATE: 'NEGATIVE_RATE',

  UNEXPECTED_UNIT: 'UNEXPECTED_UNIT',
  UNKNOWN_UNIT: 'UNKNOWN_UNIT',

  POSSIBLE_DUPLICATE: 'POSSIBLE_DUPLICATE',

  GST_EXCEEDS_TOTAL: 'GST_EXCEEDS_TOTAL',
  ZERO_CONSUMPTION: 'ZERO_CONSUMPTION',
  ZERO_QUANTITY: 'ZERO_QUANTITY',
  FUTURE_BILL_DATE: 'FUTURE_BILL_DATE',
  FUTURE_INVOICE_DATE: 'FUTURE_INVOICE_DATE',
  AMOUNT_EXCEEDS_MAX: 'AMOUNT_EXCEEDS_MAX',
  CONSUMPTION_EXCEEDS_MAX: 'CONSUMPTION_EXCEEDS_MAX',
  QUANTITY_EXCEEDS_MAX: 'QUANTITY_EXCEEDS_MAX',
} as const;

export type ValidationWarningCodeValue =
  (typeof ValidationWarningCode)[keyof typeof ValidationWarningCode];

/** Units accepted for water/gas Unit field and implied electricity/fuel units. */
export const ALLOWED_UNITS = ['kwh', 'litres', 'liters', 'tonnes', 'tons', 'kl', 'm3', 'cubic_meter'] as const;
